spring:
  application:
    name: nginxlearn-api
  flyway:
    enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: ${PORT:8080}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: nginxlearn-api

logging:
  pattern:
    correlation: "[%X{requestId:-}] "
