import { expect, test, type Page } from '@playwright/test'

async function openWithoutConsoleErrors(page: Page) {
  const errors: string[] = []
  page.on('console', (message) => {
    if (message.type() === 'error') errors.push(message.text())
  })
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  return () => expect(errors, 'browser console errors').toEqual([])
}

async function answerAndContinue(page: Page, answer: string) {
  await page.getByRole('button', { name: new RegExp(answer) }).click()
  await expect(page.getByText('Compreensão confirmada')).toBeVisible()
  await page.getByRole('button', { name: /Entendi o resultado/ }).click()
}

test('opens the workspace and copies the command when its guided step arrives', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: 'http://127.0.0.1:5180' })
  const assertNoErrors = await openWithoutConsoleErrors(page)
  await expect(page.getByRole('link', { name: /NginxLearn/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'nginx.conf' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Terminal' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Caminho da requisição' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '1. Um servidor que entrega arquivos' })).toBeVisible()
  await expect(page.getByText('Siga o passo a passo à direita')).toBeVisible()
  await answerAndContinue(page, 'No palco central')
  await answerAndContinue(page, 'root')
  await expect(page.getByText('curl -i http://localhost/', { exact: true })).toHaveCSS('user-select', 'text')
  await page.getByLabel('Copiar comando do passo 3').click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('curl -i http://localhost/')
  assertNoErrors()
})

test('guides a beginner before completing the first lesson', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: 'http://127.0.0.1:5180' })
  const assertNoErrors = await openWithoutConsoleErrors(page)
  const terminal = page.getByLabel('Comando do terminal')

  // A command entered too early is useful feedback, but it does not skip the lesson.
  await terminal.fill('curl -i http://localhost/')
  await terminal.press('Enter')
  await expect(page.getByText('HTTP/1.1 200 OK')).toBeVisible()
  await expect(page.getByText('Lição concluída')).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Conheça a bancada' })).toBeVisible()

  await page.getByRole('button', { name: /No editor/ }).click()
  await expect(page.getByText(/Ainda não/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Conheça a bancada' })).toBeVisible()
  await answerAndContinue(page, 'No palco central')
  await expect(page.getByRole('heading', { name: 'Leia a configuração como uma frase' })).toBeVisible()
  await answerAndContinue(page, 'root')
  await expect(page.getByRole('heading', { name: 'Faça sua primeira requisição' })).toBeVisible()
  await page.getByRole('button', { name: 'Executar e observar' }).click()
  await expect(page.getByText('Evidência encontrada')).toBeVisible()
  await expect(page.getByText(/O nginx recebeu a URI/)).toBeVisible()
  await page.getByRole('button', { name: /Entendi o resultado/ }).click()
  await expect(page.getByRole('heading', { name: 'Entenda o que voltou' })).toBeVisible()
  await answerAndContinue(page, 'No corpo da resposta')
  await expect(page.getByRole('heading', { name: 'Compare com um arquivo ausente' })).toBeVisible()
  await page.getByRole('button', { name: 'Executar e observar' }).click()
  await expect(page.getByText('HTTP/1.1 404 Not Found')).toBeVisible()
  await expect(page.getByText(/O servidor estava acessível/)).toBeVisible()
  await page.getByRole('button', { name: /Entendi o resultado/ }).click()
  await expect(page.getByText('Lição concluída')).toBeVisible()
  await expect(page.getByText('server localhost escolhido')).toBeVisible()
  await expect(page.getByLabel('Copiar trace')).toBeVisible()
  await expect(page.locator('.trace-card').first()).toHaveCSS('user-select', 'text')
  await page.getByRole('button', { name: 'ver tudo' }).click()
  const title = page.locator('.trace-title').first()
  const box = await title.boundingBox()
  if (!box) throw new Error('Trace title has no bounding box')
  await page.mouse.move(box.x + 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width - 2, box.y + box.height / 2, { steps: 8 })
  await page.mouse.up()
  expect(await page.evaluate(() => window.getSelection()?.toString().trim())).not.toBe('')
  await page.getByLabel('Copiar trace').click()
  await expect(page.getByLabel('Trace copiado')).toBeVisible()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('server localhost escolhido')
  assertNoErrors()
})

test('keeps an edited config pending until reload', async ({ page }) => {
  const assertNoErrors = await openWithoutConsoleErrors(page)
  const editor = page.getByLabel('Editor do nginx.conf')
  await editor.fill(`events {}
http {
  server {
    listen 80;
    return 200 "recarregou";
  }
}`)
  await expect(page.getByText('não recarregada')).toBeVisible()
  const terminal = page.getByLabel('Comando do terminal')
  await terminal.fill('nginx -t')
  await terminal.press('Enter')
  await expect(page.getByText(/test is successful/)).toBeVisible()
  await terminal.fill('nginx -s reload')
  await terminal.press('Enter')
  await expect(page.getByText('ativa', { exact: true })).toBeVisible()
  await terminal.fill('curl http://localhost/')
  await terminal.press('Enter')
  await expect(page.getByText('recarregou', { exact: true })).toBeVisible()
  assertNoErrors()
})

test('shows the request journey and reveals the response at the end', async ({ page }) => {
  await page.clock.install()
  const assertNoErrors = await openWithoutConsoleErrors(page)
  const terminal = page.getByLabel('Comando do terminal')
  await terminal.fill('curl -i http://localhost/')
  await terminal.press('Enter')
  await expect(page.locator('.request-map li')).toHaveCount(4)
  await expect(page.locator('.request-summary .status-code')).toHaveText('···')
  await page.getByRole('button', { name: 'Pausar animação' }).click()
  const progress = page.getByRole('progressbar', { name: 'Etapas da requisição' })
  const pausedAt = await progress.getAttribute('aria-valuenow')
  await page.clock.runFor(1_500)
  await expect(progress).toHaveAttribute('aria-valuenow', pausedAt ?? '')
  await page.getByRole('button', { name: 'Avançar um passo' }).click()
  await expect(progress).toHaveAttribute('aria-valuenow', String(Number(pausedAt) + 1))
  await page.getByRole('button', { name: 'ver tudo' }).click()
  await expect(page.locator('.request-summary .status-code')).toHaveText('200')
  await expect(page.locator('.request-map li[aria-current="step"]')).toContainText('Resposta 200')
  await expect.poll(async () => page.getByRole('progressbar', { name: 'Etapas da requisição' }).evaluate((element) => element.getAttribute('aria-valuenow') === element.getAttribute('aria-valuemax'))).toBe(true)
  await expect(page.getByRole('button', { name: 'Avançar um passo' })).toBeDisabled()
  await terminal.fill('curl -i http://localhost/')
  await terminal.press('Enter')
  await expect(page.locator('.request-summary .status-code')).toHaveText('···')
  await expect(page.locator('.request-map li[aria-current="step"]')).toContainText('Cliente')
  assertNoErrors()
})

test('shows the complete request immediately when reduced motion is preferred', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const assertNoErrors = await openWithoutConsoleErrors(page)
  const terminal = page.getByLabel('Comando do terminal')
  await terminal.fill('curl -i http://localhost/')
  await terminal.press('Enter')
  await expect(page.locator('.trace-playback-label')).toContainText('Percurso concluído')
  await expect(page.locator('.request-map li[aria-current="step"]')).toContainText('Resposta 200')
  await expect(page.getByRole('button', { name: 'Avançar um passo' })).toBeDisabled()
  assertNoErrors()
})

test('stacks the workspace on a phone-sized viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const assertNoErrors = await openWithoutConsoleErrors(page)
  await expect(page.getByLabel('Editor do nginx.conf')).toBeVisible()
  await expect(page.getByLabel('Comando do terminal')).toBeVisible()
  await page.locator('.campaign-menu summary').click()
  await page.getByRole('navigation', { name: 'Capítulos da loja' }).getByRole('button', { name: /A loja ganha um endereço/ }).click()
  await expect(page.getByRole('heading', { name: '3. Vários sites no mesmo servidor' })).toBeVisible()
  await expect(page.getByText('Você editou o arquivo nginx.conf. Qual ação faz a mudança responder a novas requisições?')).toBeVisible()
  assertNoErrors()
})

test('investigates the shop incident, resumes, and solves the transfer challenge', async ({ page }) => {
  const assertNoErrors = await openWithoutConsoleErrors(page)
  await page.getByRole('button', { name: 'Missão: imagens da loja' }).click()
  await expect(page.getByRole('heading', { name: 'As imagens da loja sumiram' })).toBeVisible()
  await page.getByRole('button', { name: 'Abrir a loja' }).click()
  await expect(page.getByText('GET /imagens/caneca.svg')).toBeVisible()
  await expect(page.getByText('404', { exact: true })).toBeVisible()
  expect(await page.frameLocator('iframe[title="Loja simulada"]').locator('img').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBe(0)
  await expect(page.getByRole('tab', { name: 'Mapa da requisição' })).toBeDisabled()
  await page.getByRole('button', { name: '/data/catalogo/imagens/caneca.svg' }).click()
  await expect(page.getByText(/Isso mesmo: root/)).toBeVisible()
  await page.getByRole('button', { name: 'Entendi a evidência' }).click()
  await page.getByRole('tab', { name: 'Mapa da requisição' }).focus()
  await page.getByRole('tab', { name: 'Mapa da requisição' }).press('ArrowLeft')
  await expect(page.getByRole('tab', { name: 'Loja' })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: 'Loja' }).press('ArrowRight')
  await expect(page.getByRole('tab', { name: 'Mapa da requisição' })).toHaveAttribute('aria-selected', 'true')
  const editor = page.getByLabel('Editor do nginx.conf')
  await editor.fill((await editor.inputValue()).replace('root /data/catalogo;', 'alias /data/catalogo;'))
  await page.getByRole('button', { name: 'Validar solução' }).click()
  await expect(page.getByText(/ainda não está ativa/)).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '4. Corrija e comprove' })).toBeVisible()
  await expect(page.getByLabel('Editor do nginx.conf')).toHaveValue(/alias \/data\/catalogo;/)
  await expect(page.getByText('não recarregada')).toBeVisible()
  await page.getByRole('button', { name: 'Testar nginx -t' }).click()
  await page.getByRole('button', { name: 'Recarregar nginx' }).click()
  await page.getByRole('button', { name: 'Validar solução' }).click()
  await expect(page.getByText(/Depois do reload, abra a loja novamente/)).toBeVisible()
  await page.getByRole('tab', { name: 'Mapa da requisição' }).click()
  await page.getByRole('button', { name: /Ver configuração · linha/ }).first().click()
  await expect(page.getByLabel('Editor do nginx.conf')).toHaveAttribute('readonly', '')
  await expect(page.getByLabel('Editor do nginx.conf')).toHaveValue(/root \/data\/catalogo;/)
  await page.getByRole('button', { name: 'Voltar ao editor' }).click()
  await expect(page.getByLabel('Editor do nginx.conf')).toHaveValue(/alias \/data\/catalogo;/)
  await page.getByRole('tab', { name: 'Loja' }).click()
  await page.getByRole('button', { name: 'Recarregar loja' }).click()
  await expect(page.getByText('GET /imagens/caneca.svg')).toBeVisible()
  await expect.poll(() => page.frameLocator('iframe[title="Loja simulada"]').locator('img').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Validar solução' }).click()
  await expect(page.getByRole('heading', { name: 'Você restaurou a imagem' })).toBeVisible()
  await page.getByRole('button', { name: 'Começar desafio final' }).click()
  await page.getByRole('button', { name: 'Abrir ou atualizar a loja' }).click()
  await expect(page.getByText('GET /midia/vaso.svg')).toBeVisible()
  const transferEditor = page.getByLabel('Editor do nginx.conf')
  await transferEditor.fill((await transferEditor.inputValue()).replace('root /opt/produtos;', 'alias /opt/produtos;'))
  await page.getByRole('button', { name: 'Recarregar nginx' }).click()
  await page.getByRole('button', { name: 'Abrir ou atualizar a loja' }).click()
  await page.getByRole('button', { name: 'Validar solução' }).click()
  await expect(page.getByRole('heading', { name: 'Missão concluída' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Missão concluída' })).toBeVisible()
  await page.getByLabel('Escolher lição').selectOption('0')
  await expect(page.getByRole('heading', { name: '1. Um servidor que entrega arquivos' })).toBeVisible()
  await page.getByRole('button', { name: 'Missão: imagens da loja' }).click()
  await expect(page.getByRole('heading', { name: 'Missão concluída' })).toBeVisible()
  await page.getByRole('button', { name: 'Próximo incidente: duas rotas falham' }).click()
  await expect(page.getByRole('heading', { name: 'A loja voltou, mas duas rotas falham' })).toBeVisible()
  await page.getByRole('button', { name: 'Abrir ou atualizar a loja' }).click()
  await expect(page.locator('.shop-resources').getByRole('button', { name: '404 GET /dashboard' })).toBeVisible()
  await expect(page.locator('.shop-resources').getByRole('button', { name: '404 GET / · Host: desconhecido.test' })).toBeVisible()
  await page.locator('.shop-resources').getByRole('button', { name: '404 GET /dashboard' }).click()
  await expect(page.getByRole('tab', { name: 'Mapa da requisição' })).toHaveAttribute('aria-selected', 'true')
  const integrationEditor = page.getByLabel('Editor do nginx.conf')
  await integrationEditor.fill((await integrationEditor.inputValue()).replace('root /data/catalogo;', 'alias /data/catalogo;').replace('try_files $uri $uri/ =404;', 'try_files $uri $uri/ /index.html;'))
  await page.getByRole('button', { name: 'Testar nginx -t' }).click()
  await page.getByRole('button', { name: 'Recarregar nginx' }).click()
  await page.getByRole('button', { name: 'Validar solução' }).click()
  await expect(page.getByText(/Depois do reload, abra a loja novamente/)).toBeVisible()
  await page.getByRole('button', { name: 'Abrir ou atualizar a loja' }).click()
  await page.getByRole('tab', { name: 'Loja' }).click()
  await expect(page.locator('.shop-resources').getByRole('button', { name: '200 GET /dashboard' })).toBeVisible()
  await expect(page.locator('.shop-resources').getByRole('button', { name: '404 GET / · Host: desconhecido.test' })).toBeVisible()
  await page.getByRole('button', { name: 'Validar solução' }).click()
  await expect(page.getByRole('heading', { name: 'Incidente resolvido' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Incidente resolvido' })).toBeVisible()
  assertNoErrors()
})

test('recovers from invalid saved mission data on a narrow screen', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.addInitScript(() => {
    if (window.top !== window) return
    localStorage.setItem('nginxlearn:mission-v1', '{invalid')
    localStorage.setItem('nginxlearn:last-mode-v1', 'mission')
  })
  const assertNoErrors = await openWithoutConsoleErrors(page)
  await expect(page.getByRole('heading', { name: '1. Um servidor que entrega arquivos' })).toBeVisible()
  await page.getByRole('button', { name: 'Missão: imagens da loja' }).click()
  await expect(page.getByRole('heading', { name: 'As imagens da loja sumiram' })).toBeVisible()
  await page.getByRole('button', { name: 'Abrir a loja' }).click()
  await expect(page.getByRole('heading', { name: '2. Faça uma previsão' })).toBeVisible()
  assertNoErrors()
})

test('keeps chapter progress and the edited draft when moving through the campaign map', async ({ page }) => {
  const assertNoErrors = await openWithoutConsoleErrors(page)
  await answerAndContinue(page, 'No palco central')
  await expect(page.getByRole('heading', { name: 'Leia a configuração como uma frase' })).toBeVisible()
  const editor = page.getByLabel('Editor do nginx.conf')
  await editor.fill((await editor.inputValue()).replace('index index.html;', 'index sobre.html;'))
  await page.locator('.campaign-menu summary').click()
  await page.getByRole('navigation', { name: 'Capítulos da loja' }).getByRole('button', { name: /A loja ganha um endereço/ }).click()
  await expect(page.getByRole('heading', { name: '3. Vários sites no mesmo servidor' })).toBeVisible()
  await page.getByRole('button', { name: 'Apenas salvar o arquivo' }).click()
  await expect(page.getByText('O arquivo foi salvo, mas o nginx ainda usa a configuração ativa.')).toBeVisible()
  await page.getByRole('button', { name: 'Executar um reload bem-sucedido' }).click()
  await expect(page.getByText('Correto: o reload promove a configuração válida à versão ativa.')).toBeVisible()
  await page.locator('.campaign-menu summary').click()
  await page.getByRole('navigation', { name: 'Capítulos da loja' }).getByRole('button', { name: /A loja abre as portas/ }).click()
  await expect(page.getByRole('heading', { name: 'Leia a configuração como uma frase' })).toBeVisible()
  await expect(editor).toHaveValue(/index sobre.html;/)
  await expect(page.getByText('não recarregada')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Leia a configuração como uma frase' })).toBeVisible()
  await expect(page.getByLabel('Editor do nginx.conf')).toHaveValue(/index sobre.html;/)
  await page.locator('.campaign-menu summary').click()
  await page.getByRole('navigation', { name: 'Capítulos da loja' }).getByRole('button', { name: /A loja ganha um endereço/ }).click()
  await expect(page.getByText('Correto: o reload promove a configuração válida à versão ativa.')).toBeVisible()
  assertNoErrors()
})

test('ignores a malformed chapter checkpoint without disabling the lab', async ({ page }) => {
  await page.addInitScript(() => {
    if (window.top !== window) return
    localStorage.setItem('nginxlearn:chapters-v1', '{invalid')
    localStorage.setItem('nginxlearn:guided-v2-completed', '{}')
  })
  const assertNoErrors = await openWithoutConsoleErrors(page)
  await expect(page.getByRole('heading', { name: '1. Um servidor que entrega arquivos' })).toBeVisible()
  await expect(page.getByText('O navegador não permitiu salvar.')).not.toBeVisible()
  await page.locator('.campaign-menu summary').click()
  await page.getByRole('navigation', { name: 'Capítulos da loja' }).getByRole('button', { name: /A loja ganha um endereço/ }).click()
  await expect(page.getByRole('heading', { name: '3. Vários sites no mesmo servidor' })).toBeVisible()
  assertNoErrors()
})

test('restores cache and request-limit state in the sale chapter', async ({ page }) => {
  const assertNoErrors = await openWithoutConsoleErrors(page)
  await page.locator('.campaign-menu summary').click()
  await page.getByRole('navigation', { name: 'Capítulos da loja' }).getByRole('button', { name: /Chegou o dia da promoção/ }).click()
  const terminal = page.getByLabel('Comando do terminal')
  await terminal.fill('curl -i http://localhost/')
  await terminal.press('Enter')
  await expect(page.getByText('X-Cache-Status: MISS')).toBeVisible()
  await page.locator('.campaign-menu summary').click()
  await page.getByRole('navigation', { name: 'Capítulos da loja' }).getByRole('button', { name: /A loja abre as portas/ }).click()
  await page.locator('.campaign-menu summary').click()
  await page.getByRole('navigation', { name: 'Capítulos da loja' }).getByRole('button', { name: /Chegou o dia da promoção/ }).click()
  await terminal.fill('curl -i http://localhost/')
  await terminal.press('Enter')
  await expect(page.getByText('X-Cache-Status: HIT')).toBeVisible()
  await terminal.fill('curl -i http://localhost/')
  await terminal.press('Enter')
  await expect(page.getByText('HTTP/1.1 429 Too Many Requests')).toBeVisible()
  assertNoErrors()
})
